environment:

  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python33"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python27-x64"
    - PYTHON: "C:\\Python33-x64"
    - PYTHON: "C:\\Python34-x64"

init:
  - "echo Testing with %PYTHON%"

install:
  - "powershell appveyor\\install.ps1"

build: off

test_script:
  - "%PYTHON%\\Scripts\\inv.exe test"
