[tool.mypy]
files = ["invoke", "integration", "sites"]
check_untyped_defs = true
follow_imports_for_stubs = true
# disallow_any_decorated = true
# disallow_any_generics = true
disallow_any_unimported = true
disallow_incomplete_defs = true
disallow_subclassing_any = true
# disallow_untyped_calls = true
# disallow_untyped_decorators = true
disallow_untyped_defs = true
enable_error_code = [
    "redundant-expr",
    "redundant-self",
#    "truthy-bool",
#    "truthy-iterable",
    "ignore-without-code",
#    "possibly-undefined",
    "unused-awaitable",
]
# implicit_reexport = false
no_implicit_optional = true
pretty = true
show_column_numbers = true
show_error_codes = true
strict_equality = true
warn_incomplete_stub = true
warn_redundant_casts = true
# warn_return_any = true
# warn_unreachable = true
warn_unused_ignores = true

[[tool.mypy.overrides]]
module = "invoke.vendor.*"
ignore_errors = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false


[[tool.mypy.overrides]]
module = "alabaster"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "fluidity"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "icecream"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "invocations"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "lexicon"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pytest_relaxed"
ignore_missing_imports = true
